image: rustlang/nightly-2021-03-25

default:
before_script:
  - sudo apt-get update && apt-get -y protobuf-compiler
  - sudo apt-get install gcc-10 g++-10
  - rustup override set nightly-2021-03-25
  - rustc --version
  - cargo --version

variables:
  SGX_MODE: SW
  IAS_MODE: DEV
  CC: gcc-10
  CXX: g++-10

stages:
  - build
  - test
  - lint

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-job:
  stage: build
  script:
    - echo "Building project"
    - cargo build --release

test-job:
  stage: test
  script:
    - echo "Running all unit tests"
    - cargo test --release

lint-job:
  stage: lint
  script:
    - echo "Running cargo clippy"
    - rustup component add clippy
    - cargo clippy --release -- -D warnings
  stage: lint
  script:
    - echo "Running cargo fmt on db"
    - rustup component add rustfmt
    - cargo fmt --all -- --check
